### ISSUE TITLE
Add test suite

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/avatar-elements#12]
It's my first time using ES6, so I don't know what's the best test suite for this. Any recommendations?

**Comment by jonatanrdsantos** [comment]
The [Harmonic project](https://github.com/es6rocks/harmonic/) use Mocha and jshint:
- [gulp-mocha](https://www.npmjs.com/package/gulp-mocha).
- [mocha-jshint](https://www.npmjs.com/package/mocha-jshint).

**Comment by arthurvr** [comment]
> It's my first time using ES6, so I don't know what's the best test suite for this. 

Why don't you just test your compiled code? It being originally written in ES6 doesn't make that much sense right?

And if you mean to actually write the tests in ES6, it's just javascript so you can use whatever test suite you prefer.

**Comment by zenorocha** [comment]
Of course! Thanks for the input @arthurvr ;D
