### ISSUE TITLE
Add Twitter avatar

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/avatar-elements#2]

**Comment by jonatanrdsantos** [comment]
Twitter needs [authentication](https://dev.twitter.com/rest/reference/get/users/show)

**Comment by zenorocha** [comment]
Nooooooooo!

**Comment by victorperin** [comment]
It also doesn't have any public key, like Google+ have. :cry:

**Comment by zenorocha** [comment]
In that case, we may use avatar.io.

**Comment by jonatanrdsantos** [comment]
:+1:

**Comment by victorperin** [comment]
:+1:
